version: "3.8"

services:
  loki:
    user: "root"
    container_name: loki_container
    build: ./monitoring/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./monitoring/loki/config.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:3100/ready || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - dokploy-network

  promtail:
    user: "root"
    container_name: promtail_container
    build: ./monitoring/promtail
    volumes:
      - /var/log:/var/log
      - ./monitoring/promtail/config.yaml:/etc/promtail/config.yaml
    ports:
      - "9080:9080"
    depends_on:
      loki:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "-S", "http://localhost:9080/ready"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    networks:
      - dokploy-network

  grafana:
    user: "root"
    container_name: grafana_container
    build: ./monitoring/grafana
    ports:
      - "3334:3000"
    env_file:
      - .env
    environment:
      - GF_METRICS_USERNAME=${GF_METRICS_USERNAME}
      - GF_METRICS_PASSWORD=${GF_METRICS_PASSWORD}
    volumes:
      - ./monitoring/grafana/grafana.ini:/etc/grafana/grafana.ini
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana:/etc/grafana/provisioning
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true

volumes:
  grafana-data:
  loki-data:
