"""add_access


Revision ID: 56953b6e0ceb
Revises: 803c3ecbe03c
Create Date: 2025-04-14 05:06:47.478984


"""
from typing import Sequence, Union


from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '56953b6e0ceb'
down_revision: Union[str, None] = '803c3ecbe03c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###