"""add_ai_chats

Revision ID: 7ef3efadee76
Revises: ba0ec7355fea
Create Date: 2025-05-01 23:26:08.863191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ef3efadee76'
down_revision: Union[str, None] = 'ba0ec7355fea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_chats',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_chats_chat_id'), 'ai_chats', ['chat_id'], unique=True)
    op.create_index(op.f('ix_ai_chats_user_id'), 'ai_chats', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_chats_user_id'), table_name='ai_chats')
    op.drop_index(op.f('ix_ai_chats_chat_id'), table_name='ai_chats')
    op.drop_table('ai_chats')
    # ### end Alembic commands ###
