"""add_field_is_public_for_table_access_rule_model

Revision ID: 939ff8aa993f
Revises: 7ef3efadee76
Create Date: 2025-05-02 22:19:09.898057

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "939ff8aa993f"
down_revision: Union[str, None] = "7ef3efadee76"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("access_rules", sa.Column("is_public", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("access_rules", "is_public")
    # ### end Alembic commands ###
