"""rename field schema from tables and lists

Revision ID: b3aad6bebf90
Revises: 4db7488f97e7
Create Date: 2025-03-28 21:44:49.424817

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b3aad6bebf90"
down_revision: Union[str, None] = "4db7488f97e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "list_definitions", sa.Column("list_schema", sa.JSON(), nullable=False)
    )
    op.drop_column("list_definitions", "schema")
    op.add_column(
        "table_definitions", sa.Column("table_schema", sa.JSON(), nullable=False)
    )
    op.drop_column("table_definitions", "schema")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "table_definitions",
        sa.Column(
            "schema",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("table_definitions", "table_schema")
    op.add_column(
        "list_definitions",
        sa.Column(
            "schema",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("list_definitions", "list_schema")
    # ### end Alembic commands ###
