"""settings_for_kanban

Revision ID: d9bb096846fb
Revises: b3aad6bebf90
Create Date: 2025-04-07 21:02:36.916669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9bb096846fb'
down_revision: Union[str, None] = 'b3aad6bebf90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kanban_board_settings',
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('display_settings', sa.JSON(), nullable=False),
    sa.Column('automation_settings', sa.JSON(), nullable=False),
    sa.Column('notification_settings', sa.JSON(), nullable=False),
    sa.Column('access_settings', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['kanban_boards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('board_id', 'id')
    )
    op.drop_column('kanban_boards', 'display_settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kanban_boards', sa.Column('display_settings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_table('kanban_board_settings')
    # ### end Alembic commands ###
